CREATE TABLE A00 (
  A00_CODIGO VARCHAR(6) PRIMARY KEY NOT NULL,
  A00_NOME VARCHAR(100) NOT NULL,
  A00_LOGIN VARCHAR(100) NOT NULL,
  A00_EMAIL VARCHAR(150) NOT NULL,
  A00_BLOQ CHAR(1) NOT NULL DEFAULT '1',
  A00_SENHA VARCHAR(100) NOT NULL,
  A00_GRUPO VARCHAR(6) NOT NULL,
  A00_APTO VARCHAR(8) NOT NULL,
  A00_CPF VARCHAR(11) NOT NULL,
  );

CREATE TABLE A01 (
  A01_CODIGO VARCHAR(6) PRIMARY KEY NOT NULL,
  A01_DESCRI VARCHAR(100) NOT NULL
)

CREATE TABLE A02 (
  A02_CODIGO  VARCHAR(100) PRIMARY KEY NOT NULL,
  A02_CODA00  VARCHAR(6) NOT NULL,
  A02_DATAINI DATE NOT NULL,
  A02_HORAINI TIME NOT NULL,
  A02_DATAFIM DATE NULL,
  A02_HORAFIM TIME NULL,
  A02_ISACTIVE INT NOT NULL DEFAULT 1
)

CREATE TABLE A03 (
  A03_CODIGO VARCHAR(10) PRIMARY KEY NOT NULL,
  A03_CODA00 VARCHAR(6) NOT NULL,
  A03_TITULO VARCHAR(100) NOT NULL,
  A03_DATAINC DATE NOT NULL,
  A03_HORAINC TIME NOT NULL,
  A03_DATAINI DATE NULL,
  A03_HORAINI TIME NULL,
  A03_DATAFIM DATE NULL,
  A03_HORAFIM TIME NULL,
  A03_DESCRICAO VARCHAR(MAX) NOT NULL,
  A03_MOTREJ VARCHAR(MAX) NULL,
  A03_ANEXOS VARCHAR(MAX) NULL,
  A03_STATUS CHAR(1) NOT NULL
);

CREATE TABLE A04 (
  A04_CODIGO VARCHAR(10) PRIMARY KEY NOT NULL,
  A04_CODA00 VARCHAR(6) NOT NULL,
  A04_TITULO VARCHAR(100) NOT NULL,
  A04_DESCRICAO VARCHAR(MAX) NOT NULL,
  A04_ANEXOS VARCHAR(MAX) NULL,
  A04_TIPO CHAR(1) NULL,
  A04_DATA DATE NOT NULL,
  A04_HORA TIME NOT NULL,
)

